### ISSUE TITLE
Duplicate File Load 10.2.7

### ISSUE THREAD

**Issue by Nillx** [mitchnull/Bazooka#6]
Getting this error msg after the patch release

`2x Bazooka/Bazooka.toc:26 Duplicate File Load Detected. [Bazooka/libs/LibDataBroker-1.1-4/LibDataBroker-1.1.lua] first loaded at [Bazooka/Bazooka.toc:24]`

**Comment by mitchnull** [comment]
Thanks for the report.  Should be fixed in v3.0.11
