### ISSUE TITLE
bug with latest update

### ISSUE THREAD

**Issue by Addonman** [mitchnull/Bazooka#9]
Message: Interface/AddOns/Bazooka/Bazooka.lua line 2675:
   attempt to call global 'LoadAddOn' (a nil value)
Debug:
   [string "@Interface/AddOns/Bazooka/Bazooka.lua"]:2675: loadOptions()
   [string "@Interface/AddOns/Bazooka/Bazooka.lua"]:2065:
      Interface/AddOns/Bazooka/Bazooka.lua:2052
   [string "=[C]"]: ?
   [string "@Interface/AddOns/Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:66:
      ...AddOns/Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:61
   [string "@Interface/AddOns/Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:494: InitializeAddon()
   [string "@Interface/AddOns/Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:619:
      ...AddOns/Accountant/Libs/AceAddon-3.0/AceAddon-3.0.lua:611
Locals:
self = <table> {
 attachedBars = <table> {
 }
 AttachNames = <table> {
 }
 defaultModuleState = false
 AreaNames = <table> {
 }
 numBars = 0
 bottomBottom = -1
 enabledState = true
 Plugin = <table> {
 }
 AppName = "Bazooka"
 bottomTop = 0
 db = <table> {
 }
 baseName = "Bazooka"
 plugins = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 topBottom = 0
 ldbs = <table> {
 }
 topTop = 1
 version = "Bazooka-v3.1.0"
 orderedModules = <table> {
 }
 TopAnchor = Bazooka_TopAnchor {
 }
 Defaults = <table> {
 }
 BottomAnchor = Bazooka_BottomAnchor {
 }
 modules = <table> {
 }
 name = "Bazooka"
 bars = <table> {
 }
 Bar = <table> {
 }
}
(*temporary) = nil
(*temporary) = "Bazooka_Options"
(*temporary) = "attempt to call global 'LoadAddOn' (a nil value)"
OptionsAppName = "Bazooka_Options"

**Comment by mitchnull** [comment]
should be fixed in v3.1.2
